package com.backend.Logic;

import com.backend.Logic.Nodes.GeneralNode;
import com.backend.Models.DataModel;
import com.backend.Models.GraphModel;
import com.backend.Models.NodeModel;
import il.ac.bgu.cs.bp.bpjs.execution.BProgramRunner;
import il.ac.bgu.cs.bp.bpjs.execution.listeners.PrintBProgramRunnerListener;
import il.ac.bgu.cs.bp.bpjs.model.BProgram;
import il.ac.bgu.cs.bp.bpjs.model.ResourceBProgram;
import il.ac.bgu.cs.bp.bpjs.model.StringBProgram;
import org.springframework.web.servlet.mvc.method.annotation.SseEmitter;

import java.util.*;

public class ServiceImpl implements IService {

    @Override
    public void run(GraphModel graphModel, SseEmitter emitter) {

        //TODO filter only nodes with code


        // Collect node functions
        String functions = generateAllFunctionsFromNodes(graphModel.getNodes());


        // Start a new deployment
        BProgram bprog;
        BProgramRunner rnr;
        bprog = new ResourceBProgram("rungraph.js");
        bprog.putInGlobalScope("model", graphModel);
        bprog.appendSource(functions);

        rnr = new BProgramRunner(bprog);
        //rnr.addListener(new PrintBProgramRunnerListener());
        rnr.addListener(new GraphBProgramRunnerListener(emitter));
//        if(!isTest){
//            rnr.addListener(new PrintBProgramRunnerListener());
//        }
//        else{
//            rnr.addListener(new PrintBProgramRunnerListener());
//        }

        //IFTTTReporter.listenTo(rnr);

        rnr.run();
    }

    private String generateAllFunctionsFromNodes(Map<String, NodeModel> nodes) {
        StringBuilder functions = new StringBuilder("// Autogenerated code\n");
        for(String nodeID : nodes.keySet()){
            String code = nodes.get(nodeID).getData().getCode();
            functions.append("function f").append(nodeID).append("(payload,t,bp) {\n").append(code).append("\n}\n");
        }
        return functions.toString();
    }

    @Override
    public void debug(GraphModel graphModel, SseEmitter serverEmitter) {
        return;
    }

}
